//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenamesGame.ModerationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.ModerationService.LoginRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.ModerationService.CreateLobbyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.ModerationService.CommunicationRequest))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.ModerationService.StatusCode StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.ModerationService.StatusCode StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class LoginRequest : CodenamesGame.ModerationService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateLobbyRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class CreateLobbyRequest : CodenamesGame.ModerationService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommunicationRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class CommunicationRequest : CodenamesGame.ModerationService.Request {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    public enum StatusCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPDATED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONFLICT = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_CANCEL = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_DISCONNECT = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_UNREACHABLE = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_TIMEOUT = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MISSING_DATA = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WRONG_DATA = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_FOUND = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNAUTHORIZED = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNALLOWED = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_ERROR = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_UNAVAIBLE = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_TIMEOUT = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACCOUNT_BANNED = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORT_CREATED = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORT_DUPLICATED = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USER_KICKED_AND_BANNED = 19,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModerationService.IModerationManager")]
    public interface IModerationManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModerationManager/ReportPlayer", ReplyAction="http://tempuri.org/IModerationManager/ReportPlayerResponse")]
        CodenamesGame.ModerationService.CommunicationRequest ReportPlayer(System.Guid reporterUserID, System.Guid reportedUserID, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModerationManager/ReportPlayer", ReplyAction="http://tempuri.org/IModerationManager/ReportPlayerResponse")]
        System.Threading.Tasks.Task<CodenamesGame.ModerationService.CommunicationRequest> ReportPlayerAsync(System.Guid reporterUserID, System.Guid reportedUserID, string reason);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModerationManagerChannel : CodenamesGame.ModerationService.IModerationManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModerationManagerClient : System.ServiceModel.ClientBase<CodenamesGame.ModerationService.IModerationManager>, CodenamesGame.ModerationService.IModerationManager {
        
        public ModerationManagerClient() {
        }
        
        public ModerationManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModerationManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModerationManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModerationManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CodenamesGame.ModerationService.CommunicationRequest ReportPlayer(System.Guid reporterUserID, System.Guid reportedUserID, string reason) {
            return base.Channel.ReportPlayer(reporterUserID, reportedUserID, reason);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.ModerationService.CommunicationRequest> ReportPlayerAsync(System.Guid reporterUserID, System.Guid reportedUserID, string reason) {
            return base.Channel.ReportPlayerAsync(reporterUserID, reportedUserID, reason);
        }
    }
}
