//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenamesGame.FriendService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvatarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscordUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstagramUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> PlayerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.FriendService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvatarID {
            get {
                return this.AvatarIDField;
            }
            set {
                if ((this.AvatarIDField.Equals(value) != true)) {
                    this.AvatarIDField = value;
                    this.RaisePropertyChanged("AvatarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscordUsername {
            get {
                return this.DiscordUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscordUsernameField, value) != true)) {
                    this.DiscordUsernameField = value;
                    this.RaisePropertyChanged("DiscordUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookUsername {
            get {
                return this.FacebookUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookUsernameField, value) != true)) {
                    this.FacebookUsernameField = value;
                    this.RaisePropertyChanged("FacebookUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstagramUsername {
            get {
                return this.InstagramUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.InstagramUsernameField, value) != true)) {
                    this.InstagramUsernameField = value;
                    this.RaisePropertyChanged("InstagramUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PlayerID {
            get {
                return this.PlayerIDField;
            }
            set {
                if ((this.PlayerIDField.Equals(value) != true)) {
                    this.PlayerIDField = value;
                    this.RaisePropertyChanged("PlayerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.FriendService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultSv", Namespace="http://schemas.datacontract.org/2004/07/Services")]
    [System.SerializableAttribute()]
    public partial class OperationResultSv : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendService.IFriendManager")]
    public interface IFriendManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/SearchPlayers", ReplyAction="http://tempuri.org/IFriendManager/SearchPlayersResponse")]
        CodenamesGame.FriendService.Player[] SearchPlayers(string query, System.Guid mePlayerId, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/SearchPlayers", ReplyAction="http://tempuri.org/IFriendManager/SearchPlayersResponse")]
        System.Threading.Tasks.Task<CodenamesGame.FriendService.Player[]> SearchPlayersAsync(string query, System.Guid mePlayerId, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/GetFriends", ReplyAction="http://tempuri.org/IFriendManager/GetFriendsResponse")]
        CodenamesGame.FriendService.Player[] GetFriends(System.Guid mePlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/GetFriends", ReplyAction="http://tempuri.org/IFriendManager/GetFriendsResponse")]
        System.Threading.Tasks.Task<CodenamesGame.FriendService.Player[]> GetFriendsAsync(System.Guid mePlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/GetIncomingRequests", ReplyAction="http://tempuri.org/IFriendManager/GetIncomingRequestsResponse")]
        CodenamesGame.FriendService.Player[] GetIncomingRequests(System.Guid mePlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/GetIncomingRequests", ReplyAction="http://tempuri.org/IFriendManager/GetIncomingRequestsResponse")]
        System.Threading.Tasks.Task<CodenamesGame.FriendService.Player[]> GetIncomingRequestsAsync(System.Guid mePlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendManager/SendFriendRequestResponse")]
        CodenamesGame.FriendService.OperationResultSv SendFriendRequest(System.Guid fromPlayerId, System.Guid toPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendManager/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<CodenamesGame.FriendService.OperationResultSv> SendFriendRequestAsync(System.Guid fromPlayerId, System.Guid toPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendManager/AcceptFriendRequestResponse")]
        CodenamesGame.FriendService.OperationResultSv AcceptFriendRequest(System.Guid mePlayerId, System.Guid requesterPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendManager/AcceptFriendRequestResponse")]
        System.Threading.Tasks.Task<CodenamesGame.FriendService.OperationResultSv> AcceptFriendRequestAsync(System.Guid mePlayerId, System.Guid requesterPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/RejectFriendRequest", ReplyAction="http://tempuri.org/IFriendManager/RejectFriendRequestResponse")]
        CodenamesGame.FriendService.OperationResultSv RejectFriendRequest(System.Guid mePlayerId, System.Guid requesterPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/RejectFriendRequest", ReplyAction="http://tempuri.org/IFriendManager/RejectFriendRequestResponse")]
        System.Threading.Tasks.Task<CodenamesGame.FriendService.OperationResultSv> RejectFriendRequestAsync(System.Guid mePlayerId, System.Guid requesterPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/RemoveFriend", ReplyAction="http://tempuri.org/IFriendManager/RemoveFriendResponse")]
        CodenamesGame.FriendService.OperationResultSv RemoveFriend(System.Guid mePlayerId, System.Guid friendPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/RemoveFriend", ReplyAction="http://tempuri.org/IFriendManager/RemoveFriendResponse")]
        System.Threading.Tasks.Task<CodenamesGame.FriendService.OperationResultSv> RemoveFriendAsync(System.Guid mePlayerId, System.Guid friendPlayerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendManagerChannel : CodenamesGame.FriendService.IFriendManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FriendManagerClient : System.ServiceModel.ClientBase<CodenamesGame.FriendService.IFriendManager>, CodenamesGame.FriendService.IFriendManager {
        
        public FriendManagerClient() {
        }
        
        public FriendManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FriendManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CodenamesGame.FriendService.Player[] SearchPlayers(string query, System.Guid mePlayerId, int limit) {
            return base.Channel.SearchPlayers(query, mePlayerId, limit);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.FriendService.Player[]> SearchPlayersAsync(string query, System.Guid mePlayerId, int limit) {
            return base.Channel.SearchPlayersAsync(query, mePlayerId, limit);
        }
        
        public CodenamesGame.FriendService.Player[] GetFriends(System.Guid mePlayerId) {
            return base.Channel.GetFriends(mePlayerId);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.FriendService.Player[]> GetFriendsAsync(System.Guid mePlayerId) {
            return base.Channel.GetFriendsAsync(mePlayerId);
        }
        
        public CodenamesGame.FriendService.Player[] GetIncomingRequests(System.Guid mePlayerId) {
            return base.Channel.GetIncomingRequests(mePlayerId);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.FriendService.Player[]> GetIncomingRequestsAsync(System.Guid mePlayerId) {
            return base.Channel.GetIncomingRequestsAsync(mePlayerId);
        }
        
        public CodenamesGame.FriendService.OperationResultSv SendFriendRequest(System.Guid fromPlayerId, System.Guid toPlayerId) {
            return base.Channel.SendFriendRequest(fromPlayerId, toPlayerId);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.FriendService.OperationResultSv> SendFriendRequestAsync(System.Guid fromPlayerId, System.Guid toPlayerId) {
            return base.Channel.SendFriendRequestAsync(fromPlayerId, toPlayerId);
        }
        
        public CodenamesGame.FriendService.OperationResultSv AcceptFriendRequest(System.Guid mePlayerId, System.Guid requesterPlayerId) {
            return base.Channel.AcceptFriendRequest(mePlayerId, requesterPlayerId);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.FriendService.OperationResultSv> AcceptFriendRequestAsync(System.Guid mePlayerId, System.Guid requesterPlayerId) {
            return base.Channel.AcceptFriendRequestAsync(mePlayerId, requesterPlayerId);
        }
        
        public CodenamesGame.FriendService.OperationResultSv RejectFriendRequest(System.Guid mePlayerId, System.Guid requesterPlayerId) {
            return base.Channel.RejectFriendRequest(mePlayerId, requesterPlayerId);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.FriendService.OperationResultSv> RejectFriendRequestAsync(System.Guid mePlayerId, System.Guid requesterPlayerId) {
            return base.Channel.RejectFriendRequestAsync(mePlayerId, requesterPlayerId);
        }
        
        public CodenamesGame.FriendService.OperationResultSv RemoveFriend(System.Guid mePlayerId, System.Guid friendPlayerId) {
            return base.Channel.RemoveFriend(mePlayerId, friendPlayerId);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.FriendService.OperationResultSv> RemoveFriendAsync(System.Guid mePlayerId, System.Guid friendPlayerId) {
            return base.Channel.RemoveFriendAsync(mePlayerId, friendPlayerId);
        }
    }
}
