//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenamesGame.MatchService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchService.AuthenticationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchService.SignInRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchService.ConfirmEmailRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchService.CreateLobbyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchService.JoinPartyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchService.FriendshipRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchService.CommunicationRequest))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.StatusCode StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.StatusCode StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class AuthenticationRequest : CodenamesGame.MatchService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignInRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class SignInRequest : CodenamesGame.MatchService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEmailDuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEmailValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPasswordValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUsernameDuplicateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEmailDuplicate {
            get {
                return this.IsEmailDuplicateField;
            }
            set {
                if ((this.IsEmailDuplicateField.Equals(value) != true)) {
                    this.IsEmailDuplicateField = value;
                    this.RaisePropertyChanged("IsEmailDuplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEmailValid {
            get {
                return this.IsEmailValidField;
            }
            set {
                if ((this.IsEmailValidField.Equals(value) != true)) {
                    this.IsEmailValidField = value;
                    this.RaisePropertyChanged("IsEmailValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPasswordValid {
            get {
                return this.IsPasswordValidField;
            }
            set {
                if ((this.IsPasswordValidField.Equals(value) != true)) {
                    this.IsPasswordValidField = value;
                    this.RaisePropertyChanged("IsPasswordValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUsernameDuplicate {
            get {
                return this.IsUsernameDuplicateField;
            }
            set {
                if ((this.IsUsernameDuplicateField.Equals(value) != true)) {
                    this.IsUsernameDuplicateField = value;
                    this.RaisePropertyChanged("IsUsernameDuplicate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmEmailRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class ConfirmEmailRequest : CodenamesGame.MatchService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemainingAttemptsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemainingAttempts {
            get {
                return this.RemainingAttemptsField;
            }
            set {
                if ((this.RemainingAttemptsField.Equals(value) != true)) {
                    this.RemainingAttemptsField = value;
                    this.RaisePropertyChanged("RemainingAttempts");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateLobbyRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class CreateLobbyRequest : CodenamesGame.MatchService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JoinPartyRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class JoinPartyRequest : CodenamesGame.MatchService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.Party PartyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.Party Party {
            get {
                return this.PartyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyField, value) != true)) {
                    this.PartyField = value;
                    this.RaisePropertyChanged("Party");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendshipRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class FriendshipRequest : CodenamesGame.MatchService.Request {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommunicationRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class CommunicationRequest : CodenamesGame.MatchService.Request {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    public enum StatusCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPDATED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONFLICT = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_CANCEL = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_DISCONNECT = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_UNREACHABLE = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_TIMEOUT = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MISSING_DATA = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WRONG_DATA = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_FOUND = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNAUTHORIZED = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNALLOWED = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_ERROR = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_UNAVAIBLE = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_TIMEOUT = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_UNREACHABLE = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_ERROR = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACCOUNT_BANNED = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORT_CREATED = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORT_DUPLICATED = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USER_KICKED_AND_BANNED = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRIEND_REQUEST_SENT = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRIEND_ADDED = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRIEND_REMOVED = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRIEND_REQUEST_REJECTED = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALREADY_FRIENDS = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRIEND_REQUEST_ALREADY_SENT = 27,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Party", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class Party : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.Player PartyGuestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.Player PartyHostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.Player PartyGuest {
            get {
                return this.PartyGuestField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyGuestField, value) != true)) {
                    this.PartyGuestField = value;
                    this.RaisePropertyChanged("PartyGuest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.Player PartyHost {
            get {
                return this.PartyHostField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyHostField, value) != true)) {
                    this.PartyHostField = value;
                    this.RaisePropertyChanged("PartyHost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvatarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscordUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstagramUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> PlayerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvatarID {
            get {
                return this.AvatarIDField;
            }
            set {
                if ((this.AvatarIDField.Equals(value) != true)) {
                    this.AvatarIDField = value;
                    this.RaisePropertyChanged("AvatarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscordUsername {
            get {
                return this.DiscordUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscordUsernameField, value) != true)) {
                    this.DiscordUsernameField = value;
                    this.RaisePropertyChanged("DiscordUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookUsername {
            get {
                return this.FacebookUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookUsernameField, value) != true)) {
                    this.FacebookUsernameField = value;
                    this.RaisePropertyChanged("FacebookUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstagramUsername {
            get {
                return this.InstagramUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.InstagramUsernameField, value) != true)) {
                    this.InstagramUsernameField = value;
                    this.RaisePropertyChanged("InstagramUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PlayerID {
            get {
                return this.PlayerIDField;
            }
            set {
                if ((this.PlayerIDField.Equals(value) != true)) {
                    this.PlayerIDField = value;
                    this.RaisePropertyChanged("PlayerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] BoardPlayerOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] BoardPlayerTwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.Player CompanionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MatchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.Player RequesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.MatchRules RulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] SelectedWordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] BoardPlayerOne {
            get {
                return this.BoardPlayerOneField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardPlayerOneField, value) != true)) {
                    this.BoardPlayerOneField = value;
                    this.RaisePropertyChanged("BoardPlayerOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] BoardPlayerTwo {
            get {
                return this.BoardPlayerTwoField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardPlayerTwoField, value) != true)) {
                    this.BoardPlayerTwoField = value;
                    this.RaisePropertyChanged("BoardPlayerTwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.Player Companion {
            get {
                return this.CompanionField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanionField, value) != true)) {
                    this.CompanionField = value;
                    this.RaisePropertyChanged("Companion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MatchID {
            get {
                return this.MatchIDField;
            }
            set {
                if ((this.MatchIDField.Equals(value) != true)) {
                    this.MatchIDField = value;
                    this.RaisePropertyChanged("MatchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.Player Requester {
            get {
                return this.RequesterField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterField, value) != true)) {
                    this.RequesterField = value;
                    this.RaisePropertyChanged("Requester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.MatchRules Rules {
            get {
                return this.RulesField;
            }
            set {
                if ((object.ReferenceEquals(this.RulesField, value) != true)) {
                    this.RulesField = value;
                    this.RaisePropertyChanged("Rules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SelectedWords {
            get {
                return this.SelectedWordsField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedWordsField, value) != true)) {
                    this.SelectedWordsField = value;
                    this.RaisePropertyChanged("SelectedWords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchRules", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class MatchRules : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BystanderTokensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.Gamemode GamemodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimerTokensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnTimerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BystanderTokens {
            get {
                return this.BystanderTokensField;
            }
            set {
                if ((this.BystanderTokensField.Equals(value) != true)) {
                    this.BystanderTokensField = value;
                    this.RaisePropertyChanged("BystanderTokens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.Gamemode Gamemode {
            get {
                return this.GamemodeField;
            }
            set {
                if ((this.GamemodeField.Equals(value) != true)) {
                    this.GamemodeField = value;
                    this.RaisePropertyChanged("Gamemode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimerTokens {
            get {
                return this.TimerTokensField;
            }
            set {
                if ((this.TimerTokensField.Equals(value) != true)) {
                    this.TimerTokensField = value;
                    this.RaisePropertyChanged("TimerTokens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnTimer {
            get {
                return this.TurnTimerField;
            }
            set {
                if ((this.TurnTimerField.Equals(value) != true)) {
                    this.TurnTimerField = value;
                    this.RaisePropertyChanged("TurnTimer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gamemode", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    public enum Gamemode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NORMAL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUSTOM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COUNTERINTELLIGENCE = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchRoleType", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    public enum MatchRoleType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SPYMASTER = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GUESSER = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentPickedNotification", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class AgentPickedNotification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.BoardCoordinates CoordinatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewTurnLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SenderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.BoardCoordinates Coordinates {
            get {
                return this.CoordinatesField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordinatesField, value) != true)) {
                    this.CoordinatesField = value;
                    this.RaisePropertyChanged("Coordinates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewTurnLength {
            get {
                return this.NewTurnLengthField;
            }
            set {
                if ((this.NewTurnLengthField.Equals(value) != true)) {
                    this.NewTurnLengthField = value;
                    this.RaisePropertyChanged("NewTurnLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SenderID {
            get {
                return this.SenderIDField;
            }
            set {
                if ((this.SenderIDField.Equals(value) != true)) {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoardCoordinates", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class BoardCoordinates : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Column {
            get {
                return this.ColumnField;
            }
            set {
                if ((this.ColumnField.Equals(value) != true)) {
                    this.ColumnField = value;
                    this.RaisePropertyChanged("Column");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Row {
            get {
                return this.RowField;
            }
            set {
                if ((this.RowField.Equals(value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BystanderPickedNotification", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class BystanderPickedNotification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.BoardCoordinates CoordinatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemainingTokensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SenderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.TokenType TokenToUpdateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.BoardCoordinates Coordinates {
            get {
                return this.CoordinatesField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordinatesField, value) != true)) {
                    this.CoordinatesField = value;
                    this.RaisePropertyChanged("Coordinates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemainingTokens {
            get {
                return this.RemainingTokensField;
            }
            set {
                if ((this.RemainingTokensField.Equals(value) != true)) {
                    this.RemainingTokensField = value;
                    this.RaisePropertyChanged("RemainingTokens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SenderID {
            get {
                return this.SenderIDField;
            }
            set {
                if ((this.SenderIDField.Equals(value) != true)) {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.TokenType TokenToUpdate {
            get {
                return this.TokenToUpdateField;
            }
            set {
                if ((this.TokenToUpdateField.Equals(value) != true)) {
                    this.TokenToUpdateField = value;
                    this.RaisePropertyChanged("TokenToUpdate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenType", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    public enum TokenType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TIMER = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BYSTANDER = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssassinPickedNotification", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class AssassinPickedNotification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchService.BoardCoordinates CoordinatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinalMatchLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SenderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchService.BoardCoordinates Coordinates {
            get {
                return this.CoordinatesField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordinatesField, value) != true)) {
                    this.CoordinatesField = value;
                    this.RaisePropertyChanged("Coordinates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinalMatchLength {
            get {
                return this.FinalMatchLengthField;
            }
            set {
                if ((object.ReferenceEquals(this.FinalMatchLengthField, value) != true)) {
                    this.FinalMatchLengthField = value;
                    this.RaisePropertyChanged("FinalMatchLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SenderID {
            get {
                return this.SenderIDField;
            }
            set {
                if ((this.SenderIDField.Equals(value) != true)) {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchService.IMatchManager", CallbackContract=typeof(CodenamesGame.MatchService.IMatchManagerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMatchManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/Connect", ReplyAction="http://tempuri.org/IMatchManager/ConnectResponse")]
        CodenamesGame.MatchService.CommunicationRequest Connect(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/Connect", ReplyAction="http://tempuri.org/IMatchManager/ConnectResponse")]
        System.Threading.Tasks.Task<CodenamesGame.MatchService.CommunicationRequest> ConnectAsync(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/JoinMatch", ReplyAction="http://tempuri.org/IMatchManager/JoinMatchResponse")]
        CodenamesGame.MatchService.CommunicationRequest JoinMatch(CodenamesGame.MatchService.Match match, System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/JoinMatch", ReplyAction="http://tempuri.org/IMatchManager/JoinMatchResponse")]
        System.Threading.Tasks.Task<CodenamesGame.MatchService.CommunicationRequest> JoinMatchAsync(CodenamesGame.MatchService.Match match, System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/Disconnect")]
        void Disconnect(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/Disconnect")]
        System.Threading.Tasks.Task DisconnectAsync(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/SendClue", ReplyAction="http://tempuri.org/IMatchManager/SendClueResponse")]
        void SendClue(System.Guid senderID, string clue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/SendClue", ReplyAction="http://tempuri.org/IMatchManager/SendClueResponse")]
        System.Threading.Tasks.Task SendClueAsync(System.Guid senderID, string clue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/NotifyTurnTimeout", ReplyAction="http://tempuri.org/IMatchManager/NotifyTurnTimeoutResponse")]
        void NotifyTurnTimeout(System.Guid senderID, CodenamesGame.MatchService.MatchRoleType currentRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/NotifyTurnTimeout", ReplyAction="http://tempuri.org/IMatchManager/NotifyTurnTimeoutResponse")]
        System.Threading.Tasks.Task NotifyTurnTimeoutAsync(System.Guid senderID, CodenamesGame.MatchService.MatchRoleType currentRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/NotifyPickedAgent", ReplyAction="http://tempuri.org/IMatchManager/NotifyPickedAgentResponse")]
        void NotifyPickedAgent(CodenamesGame.MatchService.AgentPickedNotification notification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/NotifyPickedAgent", ReplyAction="http://tempuri.org/IMatchManager/NotifyPickedAgentResponse")]
        System.Threading.Tasks.Task NotifyPickedAgentAsync(CodenamesGame.MatchService.AgentPickedNotification notification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/NotifyPickedBystander", ReplyAction="http://tempuri.org/IMatchManager/NotifyPickedBystanderResponse")]
        void NotifyPickedBystander(CodenamesGame.MatchService.BystanderPickedNotification notification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/NotifyPickedBystander", ReplyAction="http://tempuri.org/IMatchManager/NotifyPickedBystanderResponse")]
        System.Threading.Tasks.Task NotifyPickedBystanderAsync(CodenamesGame.MatchService.BystanderPickedNotification notification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/NotifyPickedAssassin", ReplyAction="http://tempuri.org/IMatchManager/NotifyPickedAssassinResponse")]
        void NotifyPickedAssassin(CodenamesGame.MatchService.AssassinPickedNotification notification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchManager/NotifyPickedAssassin", ReplyAction="http://tempuri.org/IMatchManager/NotifyPickedAssassinResponse")]
        System.Threading.Tasks.Task NotifyPickedAssassinAsync(CodenamesGame.MatchService.AssassinPickedNotification notification);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/NotifyClueReceived")]
        void NotifyClueReceived(string clue);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/NotifyTurnChange")]
        void NotifyTurnChange();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/NotifyRolesChanged")]
        void NotifyRolesChanged();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/NotifyGuesserTurnTimeout")]
        void NotifyGuesserTurnTimeout(int timerTokens);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/NotifyAgentPicked")]
        void NotifyAgentPicked(CodenamesGame.MatchService.AgentPickedNotification notification);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/NotifyBystanderPicked")]
        void NotifyBystanderPicked(CodenamesGame.MatchService.BystanderPickedNotification notification);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/NotifyAssassinPicked")]
        void NotifyAssassinPicked(CodenamesGame.MatchService.AssassinPickedNotification notification);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/NotifyMatchWon")]
        void NotifyMatchWon(string finalMatchLength);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/NotifyMatchTimeout")]
        void NotifyMatchTimeout(string finalMatchLength, bool isTimeOut);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/NotifyCompanionDisconnect")]
        void NotifyCompanionDisconnect();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchManager/NotifyStatsCouldNotBeSaved")]
        void NotifyStatsCouldNotBeSaved();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchManagerChannel : CodenamesGame.MatchService.IMatchManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchManagerClient : System.ServiceModel.DuplexClientBase<CodenamesGame.MatchService.IMatchManager>, CodenamesGame.MatchService.IMatchManager {
        
        public MatchManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public CodenamesGame.MatchService.CommunicationRequest Connect(System.Guid playerID) {
            return base.Channel.Connect(playerID);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.MatchService.CommunicationRequest> ConnectAsync(System.Guid playerID) {
            return base.Channel.ConnectAsync(playerID);
        }
        
        public CodenamesGame.MatchService.CommunicationRequest JoinMatch(CodenamesGame.MatchService.Match match, System.Guid playerID) {
            return base.Channel.JoinMatch(match, playerID);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.MatchService.CommunicationRequest> JoinMatchAsync(CodenamesGame.MatchService.Match match, System.Guid playerID) {
            return base.Channel.JoinMatchAsync(match, playerID);
        }
        
        public void Disconnect(System.Guid playerID) {
            base.Channel.Disconnect(playerID);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(System.Guid playerID) {
            return base.Channel.DisconnectAsync(playerID);
        }
        
        public void SendClue(System.Guid senderID, string clue) {
            base.Channel.SendClue(senderID, clue);
        }
        
        public System.Threading.Tasks.Task SendClueAsync(System.Guid senderID, string clue) {
            return base.Channel.SendClueAsync(senderID, clue);
        }
        
        public void NotifyTurnTimeout(System.Guid senderID, CodenamesGame.MatchService.MatchRoleType currentRole) {
            base.Channel.NotifyTurnTimeout(senderID, currentRole);
        }
        
        public System.Threading.Tasks.Task NotifyTurnTimeoutAsync(System.Guid senderID, CodenamesGame.MatchService.MatchRoleType currentRole) {
            return base.Channel.NotifyTurnTimeoutAsync(senderID, currentRole);
        }
        
        public void NotifyPickedAgent(CodenamesGame.MatchService.AgentPickedNotification notification) {
            base.Channel.NotifyPickedAgent(notification);
        }
        
        public System.Threading.Tasks.Task NotifyPickedAgentAsync(CodenamesGame.MatchService.AgentPickedNotification notification) {
            return base.Channel.NotifyPickedAgentAsync(notification);
        }
        
        public void NotifyPickedBystander(CodenamesGame.MatchService.BystanderPickedNotification notification) {
            base.Channel.NotifyPickedBystander(notification);
        }
        
        public System.Threading.Tasks.Task NotifyPickedBystanderAsync(CodenamesGame.MatchService.BystanderPickedNotification notification) {
            return base.Channel.NotifyPickedBystanderAsync(notification);
        }
        
        public void NotifyPickedAssassin(CodenamesGame.MatchService.AssassinPickedNotification notification) {
            base.Channel.NotifyPickedAssassin(notification);
        }
        
        public System.Threading.Tasks.Task NotifyPickedAssassinAsync(CodenamesGame.MatchService.AssassinPickedNotification notification) {
            return base.Channel.NotifyPickedAssassinAsync(notification);
        }
    }
}
