//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenamesGame.LobbyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.LobbyService.LoginRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.LobbyService.CreateLobbyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.LobbyService.JoinPartyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.LobbyService.CommunicationRequest))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.LobbyService.StatusCode StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.LobbyService.StatusCode StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class LoginRequest : CodenamesGame.LobbyService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateLobbyRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class CreateLobbyRequest : CodenamesGame.LobbyService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JoinPartyRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class JoinPartyRequest : CodenamesGame.LobbyService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.LobbyService.Party PartyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.LobbyService.Party Party {
            get {
                return this.PartyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyField, value) != true)) {
                    this.PartyField = value;
                    this.RaisePropertyChanged("Party");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommunicationRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class CommunicationRequest : CodenamesGame.LobbyService.Request {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    public enum StatusCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPDATED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONFLICT = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_DISCONNECT = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_UNREACHABLE = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MISSING_DATA = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WRONG_DATA = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_FOUND = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNAUTHORIZED = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNALLOWED = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_ERROR = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_UNAVAIBLE = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_TIMEOUT = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACCOUNT_BANNED = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORT_CREATED = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORT_DUPLICATED = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USER_KICKED_AND_BANNED = 17,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Party", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class Party : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.LobbyService.Player PartyGuestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.LobbyService.Player PartyHostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.LobbyService.Player PartyGuest {
            get {
                return this.PartyGuestField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyGuestField, value) != true)) {
                    this.PartyGuestField = value;
                    this.RaisePropertyChanged("PartyGuest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.LobbyService.Player PartyHost {
            get {
                return this.PartyHostField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyHostField, value) != true)) {
                    this.PartyHostField = value;
                    this.RaisePropertyChanged("PartyHost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvatarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscordUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstagramUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> PlayerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.LobbyService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvatarID {
            get {
                return this.AvatarIDField;
            }
            set {
                if ((this.AvatarIDField.Equals(value) != true)) {
                    this.AvatarIDField = value;
                    this.RaisePropertyChanged("AvatarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscordUsername {
            get {
                return this.DiscordUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscordUsernameField, value) != true)) {
                    this.DiscordUsernameField = value;
                    this.RaisePropertyChanged("DiscordUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookUsername {
            get {
                return this.FacebookUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookUsernameField, value) != true)) {
                    this.FacebookUsernameField = value;
                    this.RaisePropertyChanged("FacebookUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstagramUsername {
            get {
                return this.InstagramUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.InstagramUsernameField, value) != true)) {
                    this.InstagramUsernameField = value;
                    this.RaisePropertyChanged("InstagramUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PlayerID {
            get {
                return this.PlayerIDField;
            }
            set {
                if ((this.PlayerIDField.Equals(value) != true)) {
                    this.PlayerIDField = value;
                    this.RaisePropertyChanged("PlayerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.LobbyService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LobbyService.ILobbyManager", CallbackContract=typeof(CodenamesGame.LobbyService.ILobbyManagerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ILobbyManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/Connect", ReplyAction="http://tempuri.org/ILobbyManager/ConnectResponse")]
        CodenamesGame.LobbyService.CommunicationRequest Connect(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/Connect", ReplyAction="http://tempuri.org/ILobbyManager/ConnectResponse")]
        System.Threading.Tasks.Task<CodenamesGame.LobbyService.CommunicationRequest> ConnectAsync(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/Disconnect")]
        void Disconnect(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/Disconnect")]
        System.Threading.Tasks.Task DisconnectAsync(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/CreateParty", ReplyAction="http://tempuri.org/ILobbyManager/CreatePartyResponse")]
        CodenamesGame.LobbyService.CreateLobbyRequest CreateParty(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/CreateParty", ReplyAction="http://tempuri.org/ILobbyManager/CreatePartyResponse")]
        System.Threading.Tasks.Task<CodenamesGame.LobbyService.CreateLobbyRequest> CreatePartyAsync(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/InviteToParty", ReplyAction="http://tempuri.org/ILobbyManager/InviteToPartyResponse")]
        CodenamesGame.LobbyService.CommunicationRequest InviteToParty(System.Guid hostPlayerID, System.Guid friendToInviteID, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/InviteToParty", ReplyAction="http://tempuri.org/ILobbyManager/InviteToPartyResponse")]
        System.Threading.Tasks.Task<CodenamesGame.LobbyService.CommunicationRequest> InviteToPartyAsync(System.Guid hostPlayerID, System.Guid friendToInviteID, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/JoinParty", ReplyAction="http://tempuri.org/ILobbyManager/JoinPartyResponse")]
        CodenamesGame.LobbyService.JoinPartyRequest JoinParty(System.Guid joiningPlayerID, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/JoinParty", ReplyAction="http://tempuri.org/ILobbyManager/JoinPartyResponse")]
        System.Threading.Tasks.Task<CodenamesGame.LobbyService.JoinPartyRequest> JoinPartyAsync(System.Guid joiningPlayerID, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/LeaveParty")]
        void LeaveParty(System.Guid playerID, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/LeaveParty")]
        System.Threading.Tasks.Task LeavePartyAsync(System.Guid playerID, string lobbyCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/NotifyMatchInvitationReceived")]
        void NotifyMatchInvitationReceived(CodenamesGame.LobbyService.Player fromPlayer, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/NotifyMatchInvitationAccepted")]
        void NotifyMatchInvitationAccepted(CodenamesGame.LobbyService.Player byPlayer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/NotifyPartyAbandoned")]
        void NotifyPartyAbandoned(System.Guid leavingPlayerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyManagerChannel : CodenamesGame.LobbyService.ILobbyManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LobbyManagerClient : System.ServiceModel.DuplexClientBase<CodenamesGame.LobbyService.ILobbyManager>, CodenamesGame.LobbyService.ILobbyManager {
        
        public LobbyManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LobbyManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LobbyManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public CodenamesGame.LobbyService.CommunicationRequest Connect(System.Guid playerID) {
            return base.Channel.Connect(playerID);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.LobbyService.CommunicationRequest> ConnectAsync(System.Guid playerID) {
            return base.Channel.ConnectAsync(playerID);
        }
        
        public void Disconnect(System.Guid playerID) {
            base.Channel.Disconnect(playerID);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(System.Guid playerID) {
            return base.Channel.DisconnectAsync(playerID);
        }
        
        public CodenamesGame.LobbyService.CreateLobbyRequest CreateParty(System.Guid playerID) {
            return base.Channel.CreateParty(playerID);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.LobbyService.CreateLobbyRequest> CreatePartyAsync(System.Guid playerID) {
            return base.Channel.CreatePartyAsync(playerID);
        }
        
        public CodenamesGame.LobbyService.CommunicationRequest InviteToParty(System.Guid hostPlayerID, System.Guid friendToInviteID, string lobbyCode) {
            return base.Channel.InviteToParty(hostPlayerID, friendToInviteID, lobbyCode);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.LobbyService.CommunicationRequest> InviteToPartyAsync(System.Guid hostPlayerID, System.Guid friendToInviteID, string lobbyCode) {
            return base.Channel.InviteToPartyAsync(hostPlayerID, friendToInviteID, lobbyCode);
        }
        
        public CodenamesGame.LobbyService.JoinPartyRequest JoinParty(System.Guid joiningPlayerID, string lobbyCode) {
            return base.Channel.JoinParty(joiningPlayerID, lobbyCode);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.LobbyService.JoinPartyRequest> JoinPartyAsync(System.Guid joiningPlayerID, string lobbyCode) {
            return base.Channel.JoinPartyAsync(joiningPlayerID, lobbyCode);
        }
        
        public void LeaveParty(System.Guid playerID, string lobbyCode) {
            base.Channel.LeaveParty(playerID, lobbyCode);
        }
        
        public System.Threading.Tasks.Task LeavePartyAsync(System.Guid playerID, string lobbyCode) {
            return base.Channel.LeavePartyAsync(playerID, lobbyCode);
        }
    }
}
