//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenamesClient.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodenamesClient.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been permanently suspended..
        /// </summary>
        public static string banMessagePermanent {
            get {
                return ResourceManager.GetString("banMessagePermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account suspended. Time remaining: {0}.
        /// </summary>
        public static string banMessageTemporary {
            get {
                return ResourceManager.GetString("banMessageTemporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to report {0} for unsportsmanlike conduct?.
        /// </summary>
        public static string confirmReportMessage {
            get {
                return ResourceManager.GetString("confirmReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection Lost.
        /// </summary>
        public static string connectionLostTitle {
            get {
                return ResourceManager.GetString("connectionLostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, this email address is already in use.
        /// </summary>
        public static string emailCannotUseAddressAlreadyInUse {
            get {
                return ResourceManager.GetString("emailCannotUseAddressAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t confirm your email because your verification code has expired, or you ran out of attempts.
        /// </summary>
        public static string emailConfirmationCodeExpiredOrRemoved {
            get {
                return ResourceManager.GetString("emailConfirmationCodeExpiredOrRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a example@estudiantes.uv.mx.
        /// </summary>
        public static string emailEstudiantesUvMxDomain {
            get {
                return ResourceManager.GetString("emailEstudiantesUvMxDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve received your request but couldn&apos;t send you a verification code, please try again later.
        /// </summary>
        public static string emailFailedToSendCodeToUser {
            get {
                return ResourceManager.GetString("emailFailedToSendCodeToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a example@gmail.com.
        /// </summary>
        public static string emailGmailDomain {
            get {
                return ResourceManager.GetString("emailGmailDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a example@outlook.com.
        /// </summary>
        public static string emailOutlookDomain {
            get {
                return ResourceManager.GetString("emailOutlookDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t update your password because the verification code has expired or you have run out of attempts.
        /// </summary>
        public static string emailPasswordResetCodeExpiredOrRemoved {
            get {
                return ResourceManager.GetString("emailPasswordResetCodeExpiredOrRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t find this email address, please make sure the spelling is correct, try again later if the issue persists.
        /// </summary>
        public static string emailPasswordResetFailedAdressNotFound {
            get {
                return ResourceManager.GetString("emailPasswordResetFailedAdressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t update your password because we couldn&apos;t find your email, please try again later.
        /// </summary>
        public static string emailPasswordUpdateFailedAddressNotFound {
            get {
                return ResourceManager.GetString("emailPasswordUpdateFailedAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification code is incorrect you have {0} attempts remaining.
        /// </summary>
        public static string emailVerificationFailedAttemptsRemainingX {
            get {
                return ResourceManager.GetString("emailVerificationFailedAttemptsRemainingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio error.
        /// </summary>
        public static string errorAudioError {
            get {
                return ResourceManager.GetString("errorAudioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio file not found..
        /// </summary>
        public static string errorAudioFileNotFound {
            get {
                return ResourceManager.GetString("errorAudioFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your partner lost connection, the mission has been canceled..
        /// </summary>
        public static string errorCompanionLostConnection {
            get {
                return ResourceManager.GetString("errorCompanionLostConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot use a word currently on the board as a clue.
        /// </summary>
        public static string errorIllegalClue {
            get {
                return ResourceManager.GetString("errorIllegalClue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The clue must consist of a single word (letters) and a number, separated by a space. Example: &apos;Animal 3&apos;.
        /// </summary>
        public static string errorInvalidClueFormat {
            get {
                return ResourceManager.GetString("errorInvalidClueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error playing audio:.
        /// </summary>
        public static string errorPlayingAudio {
            get {
                return ResourceManager.GetString("errorPlayingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend added successfully..
        /// </summary>
        public static string friendAddedSuccess {
            get {
                return ResourceManager.GetString("friendAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are already friends with this user..
        /// </summary>
        public static string friendErrorAlreadyFriends {
            get {
                return ResourceManager.GetString("friendErrorAlreadyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not complete the friendship operation..
        /// </summary>
        public static string friendErrorOperationFailed {
            get {
                return ResourceManager.GetString("friendErrorOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot send a request to yourself..
        /// </summary>
        public static string friendErrorSelfRequest {
            get {
                return ResourceManager.GetString("friendErrorSelfRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} accepted your friend request!.
        /// </summary>
        public static string friendNotificationAccepted {
            get {
                return ResourceManager.GetString("friendNotificationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New friend request from {0}!.
        /// </summary>
        public static string friendNotificationNewRequest {
            get {
                return ResourceManager.GetString("friendNotificationNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} rejected your friend request..
        /// </summary>
        public static string friendNotificationRejected {
            get {
                return ResourceManager.GetString("friendNotificationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has removed you from their friends list..
        /// </summary>
        public static string friendNotificationRemoved {
            get {
                return ResourceManager.GetString("friendNotificationRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending.
        /// </summary>
        public static string friendPending {
            get {
                return ResourceManager.GetString("friendPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend removed successfully..
        /// </summary>
        public static string friendRemovedSuccess {
            get {
                return ResourceManager.GetString("friendRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request rejected..
        /// </summary>
        public static string friendRequestRejected {
            get {
                return ResourceManager.GetString("friendRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request sent successfully..
        /// </summary>
        public static string friendRequestSentSuccess {
            get {
                return ResourceManager.GetString("friendRequestSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose a gamemode.
        /// </summary>
        public static string gamemodeChooseAGamemode {
            get {
                return ResourceManager.GetString("gamemodeChooseAGamemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Counterintelligence mode.
        /// </summary>
        public static string gamemodeCounterintelligenceMode {
            get {
                return ResourceManager.GetString("gamemodeCounterintelligenceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom game.
        /// </summary>
        public static string gamemodeCustomGame {
            get {
                return ResourceManager.GetString("gamemodeCustomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal game.
        /// </summary>
        public static string gamemodeNormalGame {
            get {
                return ResourceManager.GetString("gamemodeNormalGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string globalBack {
            get {
                return ResourceManager.GetString("globalBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string globalCancel {
            get {
                return ResourceManager.GetString("globalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Something went wrong and your request couldn&apos;t be processed, please contact the developers if the issue persists.
        /// </summary>
        public static string globalClientError {
            get {
                return ResourceManager.GetString("globalClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string globalConfirm {
            get {
                return ResourceManager.GetString("globalConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You lost connection to the Codenames: Duet Server. Please try again later.
        /// </summary>
        public static string globalConnectionLost {
            get {
                return ResourceManager.GetString("globalConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The connection to the server has been lost..
        /// </summary>
        public static string globalDisconnected {
            get {
                return ResourceManager.GetString("globalDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we couldn&apos;t find your profile. Contact an administrator if the issue persists.
        /// </summary>
        public static string globalErrorProfileNotFound {
            get {
                return ResourceManager.GetString("globalErrorProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string globalErrorTitle {
            get {
                return ResourceManager.GetString("globalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string globalFriends {
            get {
                return ResourceManager.GetString("globalFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string globalGuest {
            get {
                return ResourceManager.GetString("globalGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string globalInformationTitle {
            get {
                return ResourceManager.GetString("globalInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid data.
        /// </summary>
        public static string globalInvalidData {
            get {
                return ResourceManager.GetString("globalInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has invited you to their lobby, join them?.
        /// </summary>
        public static string globalInvitationReceivedMessage {
            get {
                return ResourceManager.GetString("globalInvitationReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been invited to party.
        /// </summary>
        public static string globalInvitationReceivedTitle {
            get {
                return ResourceManager.GetString("globalInvitationReceivedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string globalPlay {
            get {
                return ResourceManager.GetString("globalPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t load your profile picture, is possible your game installation is corrupted.
        /// </summary>
        public static string globalProfilePictureError {
            get {
                return ResourceManager.GetString("globalProfilePictureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string globalSave {
            get {
                return ResourceManager.GetString("globalSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scoreboards.
        /// </summary>
        public static string globalScoreboards {
            get {
                return ResourceManager.GetString("globalScoreboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we couldn&apos;t process your request due to an error on our end, please try again later.
        /// </summary>
        public static string globalServerError {
            get {
                return ResourceManager.GetString("globalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we couldn&apos;t find the Codenames: Duet server, it might be offline or down for maintenance. Please try again later.
        /// </summary>
        public static string globalServerNotFound {
            get {
                return ResourceManager.GetString("globalServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seems like the Codenames: Duet server took too long answer, please try again.
        /// </summary>
        public static string globalServerTimeout {
            get {
                return ResourceManager.GetString("globalServerTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string globalSettings {
            get {
                return ResourceManager.GetString("globalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string globalStart {
            get {
                return ResourceManager.GetString("globalStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        public static string globalSuccessTitle {
            get {
                return ResourceManager.GetString("globalSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} hour(s) and {1} minute(s).
        /// </summary>
        public static string globalTimeFormat {
            get {
                return ResourceManager.GetString("globalTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, the Codenames: Duet server seems to be unavailable, please try again later.
        /// </summary>
        public static string globalTimeoutError {
            get {
                return ResourceManager.GetString("globalTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unknown error occurred.
        /// </summary>
        public static string globalUnknownError {
            get {
                return ResourceManager.GetString("globalUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we couldn&apos;t process your request due to an unknown error.
        /// </summary>
        public static string globalUnknownServerError {
            get {
                return ResourceManager.GetString("globalUnknownServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string globalUsername {
            get {
                return ResourceManager.GetString("globalUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string globalWarningTitle {
            get {
                return ResourceManager.GetString("globalWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have logged-in in another device, you will return to the login page.
        /// </summary>
        public static string kickMessageDuplicateLogin {
            get {
                return ResourceManager.GetString("kickMessageDuplicateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been permanently banned due to repeated misconduct..
        /// </summary>
        public static string kickMessagePerm {
            get {
                return ResourceManager.GetString("kickMessagePerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been kicked due to report accumulation. A temporary ban has been applied..
        /// </summary>
        public static string kickMessageTemp {
            get {
                return ResourceManager.GetString("kickMessageTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsion.
        /// </summary>
        public static string kickTitle {
            get {
                return ResourceManager.GetString("kickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select language.
        /// </summary>
        public static string langSelectLanguage {
            get {
                return ResourceManager.GetString("langSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string langSpanish {
            get {
                return ResourceManager.GetString("langSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are already connected to Codenames Matchmaking Service.
        /// </summary>
        public static string lobbyAlreadyConnectedToMatchmakingService {
            get {
                return ResourceManager.GetString("lobbyAlreadyConnectedToMatchmakingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t start a match because your companion has lost connection to the Codenames Matchmaking Service..
        /// </summary>
        public static string lobbyCantStartCompanionDisconnect {
            get {
                return ResourceManager.GetString("lobbyCantStartCompanionDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t start a match because you or your companion are already awaiting to begin a match..
        /// </summary>
        public static string lobbyCantStartPlayerBusy {
            get {
                return ResourceManager.GetString("lobbyCantStartPlayerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are already connected to the Lobby Service of Codenames.
        /// </summary>
        public static string lobbyErrorAlreadyConnected {
            get {
                return ResourceManager.GetString("lobbyErrorAlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are already in a party, leave your current party to start a new lobby.
        /// </summary>
        public static string lobbyErrorAlreadyPartyHost {
            get {
                return ResourceManager.GetString("lobbyErrorAlreadyPartyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot invite a new player, your party is full.
        /// </summary>
        public static string lobbyErrorCannotInviteNewGuest {
            get {
                return ResourceManager.GetString("lobbyErrorCannotInviteNewGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No lobby matching this code was found, please try again.
        /// </summary>
        public static string lobbyErrorLobbyCodeNotFound {
            get {
                return ResourceManager.GetString("lobbyErrorLobbyCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t join this lobby because it&apos;s already full.
        /// </summary>
        public static string lobbyErrorLobbyFull {
            get {
                return ResourceManager.GetString("lobbyErrorLobbyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t put you in this lobby because the party&apos;s host has lost connection.
        /// </summary>
        public static string lobbyErrorPartyHostNotFound {
            get {
                return ResourceManager.GetString("lobbyErrorPartyHostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t invite this player because we couldn&apos;t find your party or your player profile, please try again later.
        /// </summary>
        public static string lobbyErrorPartyOrHostNotFound {
            get {
                return ResourceManager.GetString("lobbyErrorPartyOrHostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t put you in this party because we couldn&apos;t found your profile, please try again later.
        /// </summary>
        public static string lobbyErrorProfileNotFoundWhenJoining {
            get {
                return ResourceManager.GetString("lobbyErrorProfileNotFoundWhenJoining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t send an invitation because you have lost connection to Codenames&apos; lobby service, please try again later.
        /// </summary>
        public static string lobbyErrorServiceConnectionLost {
            get {
                return ResourceManager.GetString("lobbyErrorServiceConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot invite another player because you&apos;re not your current party&apos;s host.
        /// </summary>
        public static string lobbyErrorYouAreNotPartyHost {
            get {
                return ResourceManager.GetString("lobbyErrorYouAreNotPartyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your friend is offline, we sent an invitation to your friend&apos;s email.
        /// </summary>
        public static string lobbyInfoFriendNotOnlineEmailSent {
            get {
                return ResourceManager.GetString("lobbyInfoFriendNotOnlineEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        public static string lobbyInvite {
            get {
                return ResourceManager.GetString("lobbyInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string lobbyJoin {
            get {
                return ResourceManager.GetString("lobbyJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby code: {0}.
        /// </summary>
        public static string lobbyLobyCode {
            get {
                return ResourceManager.GetString("lobbyLobyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The match has been cancelled by your companion.
        /// </summary>
        public static string lobbyMatchCanceledByCompanion {
            get {
                return ResourceManager.GetString("lobbyMatchCanceledByCompanion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The match has been cancelled because we didn&apos;t receive you or your companion&apos;s &quot;Ready!&quot; in time..
        /// </summary>
        public static string lobbyMatchCanceledTimeout {
            get {
                return ResourceManager.GetString("lobbyMatchCanceledTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t create your match because your request is missing necessary information.
        /// </summary>
        public static string lobbyMatchMissingData {
            get {
                return ResourceManager.GetString("lobbyMatchMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only the party host can start the match.
        /// </summary>
        public static string lobbyOnlyPartyHostCanStart {
            get {
                return ResourceManager.GetString("lobbyOnlyPartyHostCanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rules.
        /// </summary>
        public static string lobbyRules {
            get {
                return ResourceManager.GetString("lobbyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send code.
        /// </summary>
        public static string lobbySendCode {
            get {
                return ResourceManager.GetString("lobbySendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a lobby.
        /// </summary>
        public static string lobbyStartLobby {
            get {
                return ResourceManager.GetString("lobbyStartLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type the lobby&apos;s code.
        /// </summary>
        public static string lobbyTypeLobbyCode {
            get {
                return ResourceManager.GetString("lobbyTypeLobbyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are already logged in on another device, please log out of that device before logging in here.
        /// </summary>
        public static string loginAlreadyLoggedInError {
            get {
                return ResourceManager.GetString("loginAlreadyLoggedInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve sent a 6-digit code to:.
        /// </summary>
        public static string loginCode6DigitsSent {
            get {
                return ResourceManager.GetString("loginCode6DigitsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don&apos;t have an account?.
        /// </summary>
        public static string loginDontHaveAccount {
            get {
                return ResourceManager.GetString("loginDontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password.
        /// </summary>
        public static string loginForgotPassword {
            get {
                return ResourceManager.GetString("loginForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string loginGuest {
            get {
                return ResourceManager.GetString("loginGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log-In.
        /// </summary>
        public static string loginLogIn {
            get {
                return ResourceManager.GetString("loginLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string loginPassword {
            get {
                return ResourceManager.GetString("loginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *password required.
        /// </summary>
        public static string loginPasswordRequired {
            get {
                return ResourceManager.GetString("loginPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *password is too long.
        /// </summary>
        public static string loginPasswordTooLong {
            get {
                return ResourceManager.GetString("loginPasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as a guest.
        /// </summary>
        public static string loginPlayAsGuest {
            get {
                return ResourceManager.GetString("loginPlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign-In.
        /// </summary>
        public static string loginSignIn {
            get {
                return ResourceManager.GetString("loginSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *username required.
        /// </summary>
        public static string loginUsernameRequired {
            get {
                return ResourceManager.GetString("loginUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *username is too long.
        /// </summary>
        public static string loginUsernameTooLong {
            get {
                return ResourceManager.GetString("loginUsernameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code.
        /// </summary>
        public static string loginVerificationCode {
            get {
                return ResourceManager.GetString("loginVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check email.
        /// </summary>
        public static string loginVerifyEmail {
            get {
                return ResourceManager.GetString("loginVerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *wrong username or password, please try again.
        /// </summary>
        public static string loginWrongCredentials {
            get {
                return ResourceManager.GetString("loginWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, guest accounts cannot access this feature.
        /// </summary>
        public static string mainMenuGuestCannotAccess {
            get {
                return ResourceManager.GetString("mainMenuGuestCannotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logged-in as:.
        /// </summary>
        public static string mainMenuLoggedIn {
            get {
                return ResourceManager.GetString("mainMenuLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string mainMenuPlayer {
            get {
                return ResourceManager.GetString("mainMenuPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit.
        /// </summary>
        public static string mainMenuQuit {
            get {
                return ResourceManager.GetString("mainMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bystander tokens.
        /// </summary>
        public static string matchBystanderTokens {
            get {
                return ResourceManager.GetString("matchBystanderTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chronometer.
        /// </summary>
        public static string matchChronometer {
            get {
                return ResourceManager.GetString("matchChronometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} is the spymaster.
        /// </summary>
        public static string matchCompanionIsSpymaster {
            get {
                return ResourceManager.GetString("matchCompanionIsSpymaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ve lost connection to the Codenames: Duet match service, you will return to the lobby.
        /// </summary>
        public static string matchConnectionLostMatchCancelled {
            get {
                return ResourceManager.GetString("matchConnectionLostMatchCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Defeat.
        /// </summary>
        public static string matchDefeat {
            get {
                return ResourceManager.GetString("matchDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} was eliminated, you&apos;ve been compromised. Mission failed.
        /// </summary>
        public static string matchDefeatAssassinCompanion {
            get {
                return ResourceManager.GetString("matchDefeatAssassinCompanion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been eliminated by an assassin. Mission failed.
        /// </summary>
        public static string matchDefeatAssassinMessage {
            get {
                return ResourceManager.GetString("matchDefeatAssassinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time and operational resources have been exhausted. Mission aborted..
        /// </summary>
        public static string matchDefeatTimeoutMessage {
            get {
                return ResourceManager.GetString("matchDefeatTimeoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Too many witnesses involved, operation compromised. Mission aborted.
        /// </summary>
        public static string matchDefeatWitnessesInvolved {
            get {
                return ResourceManager.GetString("matchDefeatWitnessesInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Party.
        /// </summary>
        public static string matchParty {
            get {
                return ResourceManager.GetString("matchParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick keywords according to {0}&apos;s clue.
        /// </summary>
        public static string matchPickKeywords {
            get {
                return ResourceManager.GetString("matchPickKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        public static string matchReport {
            get {
                return ResourceManager.GetString("matchReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skip turn.
        /// </summary>
        public static string matchSkipTurn {
            get {
                return ResourceManager.GetString("matchSkipTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timer.
        /// </summary>
        public static string matchTimer {
            get {
                return ResourceManager.GetString("matchTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timer tokens.
        /// </summary>
        public static string matchTimerTokens {
            get {
                return ResourceManager.GetString("matchTimerTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turn timer.
        /// </summary>
        public static string matchTurnTimer {
            get {
                return ResourceManager.GetString("matchTurnTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type a clue so that {0} picks your keycard&apos;s agents.
        /// </summary>
        public static string matchTypeAClue {
            get {
                return ResourceManager.GetString("matchTypeAClue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victory!.
        /// </summary>
        public static string matchVictory {
            get {
                return ResourceManager.GetString("matchVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All agents found. Mission complete.
        /// </summary>
        public static string matchVictoryMessage {
            get {
                return ResourceManager.GetString("matchVictoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wait to receive the clue from your partner.
        /// </summary>
        public static string matchWaitForClue {
            get {
                return ResourceManager.GetString("matchWaitForClue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wait for you companion to pick cards.
        /// </summary>
        public static string matchWaitForCompanion {
            get {
                return ResourceManager.GetString("matchWaitForCompanion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are the spymaster.
        /// </summary>
        public static string matchYouAreSpymaster {
            get {
                return ResourceManager.GetString("matchYouAreSpymaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your keycard.
        /// </summary>
        public static string matchYourkeycard {
            get {
                return ResourceManager.GetString("matchYourkeycard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authentication required.
        /// </summary>
        public static string profileAuthenticationRequired {
            get {
                return ResourceManager.GetString("profileAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string profileChangePassword {
            get {
                return ResourceManager.GetString("profileChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t update your profile because one or more fields are not valid, please check and try again.
        /// </summary>
        public static string profileCouldNotUpdateCheckData {
            get {
                return ResourceManager.GetString("profileCouldNotUpdateCheckData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string profileEmail {
            get {
                return ResourceManager.GetString("profileEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t update your profile because we couldn&apos;t find it, please try again later. Contact an administrator if the issue persists.
        /// </summary>
        public static string profileErrorCouldNotFindProfile {
            get {
                return ResourceManager.GetString("profileErrorCouldNotFindProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we couldn&apos;t update your profile because this email or username is already in use.
        /// </summary>
        public static string profileErrorEmailOrUsernameInUse {
            get {
                return ResourceManager.GetString("profileErrorEmailOrUsernameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, this username is already in use.
        /// </summary>
        public static string profileErrorUsernameAlreadyInUse {
            get {
                return ResourceManager.GetString("profileErrorUsernameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        public static string profileLastName {
            get {
                return ResourceManager.GetString("profileLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string profileName {
            get {
                return ResourceManager.GetString("profileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new password is not valid.
        /// </summary>
        public static string profileNewPasswordNotValid {
            get {
                return ResourceManager.GetString("profileNewPasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name (optional).
        /// </summary>
        public static string profileOptionalLastName {
            get {
                return ResourceManager.GetString("profileOptionalLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name (Optional).
        /// </summary>
        public static string profileOptionalName {
            get {
                return ResourceManager.GetString("profileOptionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password is not correct.
        /// </summary>
        public static string profilePasswordErrorTypedPasswordIncorrect {
            get {
                return ResourceManager.GetString("profilePasswordErrorTypedPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password has been updated.
        /// </summary>
        public static string profilePasswordHasBeenUpdated {
            get {
                return ResourceManager.GetString("profilePasswordHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string profileProfile {
            get {
                return ResourceManager.GetString("profileProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is a sensible operation.
        /// </summary>
        public static string profileSensibleOperation {
            get {
                return ResourceManager.GetString("profileSensibleOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social media links only support 30 characters.
        /// </summary>
        public static string profileSocialNetwork {
            get {
                return ResourceManager.GetString("profileSocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please type your current password.
        /// </summary>
        public static string profileTypeCurrentPassword {
            get {
                return ResourceManager.GetString("profileTypeCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we couldn&apos;t update your profile because we couldn&apos;t find it, contact an administrator if the issue persists.
        /// </summary>
        public static string profileUpdateErrorProfileNotFound {
            get {
                return ResourceManager.GetString("profileUpdateErrorProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your profile has been updated.
        /// </summary>
        public static string profileUpdateSucessful {
            get {
                return ResourceManager.GetString("profileUpdateSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The maximum username length is 20 characters.
        /// </summary>
        public static string profileUsernameMaxLength {
            get {
                return ResourceManager.GetString("profileUsernameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have already reported this player..
        /// </summary>
        public static string reportDuplicate {
            get {
                return ResourceManager.GetString("reportDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player reported successfully..
        /// </summary>
        public static string reportSuccess {
            get {
                return ResourceManager.GetString("reportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report received. The player has been sanctioned and removed from the game..
        /// </summary>
        public static string reportUserBanned {
            get {
                return ResourceManager.GetString("reportUserBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string resetChangePassword {
            get {
                return ResourceManager.GetString("resetChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve sent a code to your email. Please check your inbox and enter it where requested..
        /// </summary>
        public static string resetCodeSend {
            get {
                return ResourceManager.GetString("resetCodeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not send code.
        /// </summary>
        public static string resetCodeSendFailed {
            get {
                return ResourceManager.GetString("resetCodeSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Associated email.
        /// </summary>
        public static string resetEmail {
            get {
                return ResourceManager.GetString("resetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter username and email.
        /// </summary>
        public static string resetMissingUserOrEmail {
            get {
                return ResourceManager.GetString("resetMissingUserOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string resetNewPassword {
            get {
                return ResourceManager.GetString("resetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not change password.
        /// </summary>
        public static string resetPasswordChangeFailed {
            get {
                return ResourceManager.GetString("resetPasswordChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be between 10 and 16 characters.
        /// </summary>
        public static string resetPasswordLengthInvalid {
            get {
                return ResourceManager.GetString("resetPasswordLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        public static string resetPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("resetPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Received code.
        /// </summary>
        public static string resetReceivedCode {
            get {
                return ResourceManager.GetString("resetReceivedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send code.
        /// </summary>
        public static string resetSendCode {
            get {
                return ResourceManager.GetString("resetSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset password.
        /// </summary>
        public static string resetTitle {
            get {
                return ResourceManager.GetString("resetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More assassins revealed.
        /// </summary>
        public static string scoresAssassins {
            get {
                return ResourceManager.GetString("scoresAssassins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assassins Revealed.
        /// </summary>
        public static string scoresAssassinsRevealed {
            get {
                return ResourceManager.GetString("scoresAssassinsRevealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fastest games.
        /// </summary>
        public static string scoresFastest {
            get {
                return ResourceManager.GetString("scoresFastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More games won.
        /// </summary>
        public static string scoresMostWins {
            get {
                return ResourceManager.GetString("scoresMostWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My score.
        /// </summary>
        public static string scoresMyScore {
            get {
                return ResourceManager.GetString("scoresMyScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record Time.
        /// </summary>
        public static string scoresRecordTime {
            get {
                return ResourceManager.GetString("scoresRecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh.
        /// </summary>
        public static string scoresRefresh {
            get {
                return ResourceManager.GetString("scoresRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wins.
        /// </summary>
        public static string scoresWins {
            get {
                return ResourceManager.GetString("scoresWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accepted email addresses:.
        /// </summary>
        public static string signInAcceptedEmailDomains {
            get {
                return ResourceManager.GetString("signInAcceptedEmailDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code must have 6 digits..
        /// </summary>
        public static string signInCodeMustHave6Digits {
            get {
                return ResourceManager.GetString("signInCodeMustHave6Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string signInConfirmPassword {
            get {
                return ResourceManager.GetString("signInConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email format is invalid.
        /// </summary>
        public static string signInEmailInvalidFormat {
            get {
                return ResourceManager.GetString("signInEmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is required.
        /// </summary>
        public static string signInEmailRequired {
            get {
                return ResourceManager.GetString("signInEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error confirming registration: .
        /// </summary>
        public static string signInErrorConfirmingRegistration {
            get {
                return ResourceManager.GetString("signInErrorConfirmingRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we couldn&apos;t sign you in because your request is missing key information.
        /// </summary>
        public static string signInErrorMissingData {
            get {
                return ResourceManager.GetString("signInErrorMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error starting registration: .
        /// </summary>
        public static string signInErrorStartingRegistration {
            get {
                return ResourceManager.GetString("signInErrorStartingRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The maximum length of the first name is 20 characters.
        /// </summary>
        public static string signInFirstNameMaxLength {
            get {
                return ResourceManager.GetString("signInFirstNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name may contain letters (with accents) and spaces only.
        /// </summary>
        public static string signInFirstNameOnlyLettersSpacesAccents {
            get {
                return ResourceManager.GetString("signInFirstNameOnlyLettersSpacesAccents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name is required.
        /// </summary>
        public static string signInFirstNameRequired {
            get {
                return ResourceManager.GetString("signInFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid password..
        /// </summary>
        public static string signInInvalidPassword {
            get {
                return ResourceManager.GetString("signInInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The maximum length of the last name is 30 characters.
        /// </summary>
        public static string signInLastNameMaxLength {
            get {
                return ResourceManager.GetString("signInLastNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name may contain letters (with accents) and spaces only.
        /// </summary>
        public static string signInLastNameOnlyLettersSpacesAccents {
            get {
                return ResourceManager.GetString("signInLastNameOnlyLettersSpacesAccents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los apellidos son obligatorios.
        /// </summary>
        public static string signInLastNameRequired {
            get {
                return ResourceManager.GetString("signInLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are not pending requests..
        /// </summary>
        public static string signInNoPendingRequests {
            get {
                return ResourceManager.GetString("signInNoPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one digit.
        /// </summary>
        public static string signInPasswordAtLeastOneDigit {
            get {
                return ResourceManager.GetString("signInPasswordAtLeastOneDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one lowercase letter.
        /// </summary>
        public static string signInPasswordAtLeastOneLowercaseLetter {
            get {
                return ResourceManager.GetString("signInPasswordAtLeastOneLowercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one special character.
        /// </summary>
        public static string signInPasswordAtLeastOneSpecialCharacter {
            get {
                return ResourceManager.GetString("signInPasswordAtLeastOneSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one uppercase letter.
        /// </summary>
        public static string signInPasswordAtLeastOneUppercaseLetter {
            get {
                return ResourceManager.GetString("signInPasswordAtLeastOneUppercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be at most {0} characters.
        /// </summary>
        public static string signInPasswordMaxLength {
            get {
                return ResourceManager.GetString("signInPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be at least {0} characters.
        /// </summary>
        public static string signInPasswordMinLength {
            get {
                return ResourceManager.GetString("signInPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must not contain more than 3 consecutive digits.
        /// </summary>
        public static string signInPasswordNotContainMoreThan3ConsecutiveDigits {
            get {
                return ResourceManager.GetString("signInPasswordNotContainMoreThan3ConsecutiveDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is required.
        /// </summary>
        public static string signInPasswordRequired {
            get {
                return ResourceManager.GetString("signInPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password requirements.
        /// </summary>
        public static string signInPasswordRequirements {
            get {
                return ResourceManager.GetString("signInPasswordRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        public static string signInPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("signInPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string signInRegister {
            get {
                return ResourceManager.GetString("signInRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration could not be started..
        /// </summary>
        public static string signInRegistrationCouldNotBeStarted {
            get {
                return ResourceManager.GetString("signInRegistrationCouldNotBeStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We just signed you in, welcome agent {0}!.
        /// </summary>
        public static string signInSuccessfulWelcome {
            get {
                return ResourceManager.GetString("signInSuccessfulWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username is required.
        /// </summary>
        public static string signInUsernameRequired {
            get {
                return ResourceManager.GetString("signInUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string socialAccept {
            get {
                return ResourceManager.GetString("socialAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string socialAddFriend {
            get {
                return ResourceManager.GetString("socialAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete friend.
        /// </summary>
        public static string socialDeleteFriend {
            get {
                return ResourceManager.GetString("socialDeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject.
        /// </summary>
        public static string socialReject {
            get {
                return ResourceManager.GetString("socialReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requests.
        /// </summary>
        public static string socialRequests {
            get {
                return ResourceManager.GetString("socialRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search for a friend.
        /// </summary>
        public static string socialSearchForAFriend {
            get {
                return ResourceManager.GetString("socialSearchForAFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search results.
        /// </summary>
        public static string socialSearchResults {
            get {
                return ResourceManager.GetString("socialSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Effects.
        /// </summary>
        public static string soundGameEffects {
            get {
                return ResourceManager.GetString("soundGameEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master Volume.
        /// </summary>
        public static string soundMasterVolume {
            get {
                return ResourceManager.GetString("soundMasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music Volume.
        /// </summary>
        public static string soundMusicVolume {
            get {
                return ResourceManager.GetString("soundMusicVolume", resourceCulture);
            }
        }
    }
}
