//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenamesClient.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodenamesClient.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose a gamemode.
        /// </summary>
        public static string gamemodeChooseAGamemode {
            get {
                return ResourceManager.GetString("gamemodeChooseAGamemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Counterintelligence mode.
        /// </summary>
        public static string gamemodeCounterintelligenceMode {
            get {
                return ResourceManager.GetString("gamemodeCounterintelligenceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom game.
        /// </summary>
        public static string gamemodeCustomGame {
            get {
                return ResourceManager.GetString("gamemodeCustomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal game.
        /// </summary>
        public static string gamemodeNormalGame {
            get {
                return ResourceManager.GetString("gamemodeNormalGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string globalBack {
            get {
                return ResourceManager.GetString("globalBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string globalCancel {
            get {
                return ResourceManager.GetString("globalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string globalConfirm {
            get {
                return ResourceManager.GetString("globalConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t connect you to the Codenames: Duet Server. Please try again later.
        /// </summary>
        public static string globalConnectionLost {
            get {
                return ResourceManager.GetString("globalConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string globalFriends {
            get {
                return ResourceManager.GetString("globalFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string globalGuest {
            get {
                return ResourceManager.GetString("globalGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid data.
        /// </summary>
        public static string globalInvalidData {
            get {
                return ResourceManager.GetString("globalInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string globalPlay {
            get {
                return ResourceManager.GetString("globalPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t load your profile picture, is possible your game installation is corrupted.
        /// </summary>
        public static string globalProfilePictureError {
            get {
                return ResourceManager.GetString("globalProfilePictureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string globalSave {
            get {
                return ResourceManager.GetString("globalSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scoreboards.
        /// </summary>
        public static string globalScoreboards {
            get {
                return ResourceManager.GetString("globalScoreboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we couldn&apos;t process your request due to an error on our end, please try again later.
        /// </summary>
        public static string globalServerError {
            get {
                return ResourceManager.GetString("globalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string globalSettings {
            get {
                return ResourceManager.GetString("globalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string globalStart {
            get {
                return ResourceManager.GetString("globalStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we couldn&apos;t process your request due to an unknown error.
        /// </summary>
        public static string globalUnknownServerError {
            get {
                return ResourceManager.GetString("globalUnknownServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string globalUsername {
            get {
                return ResourceManager.GetString("globalUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select language.
        /// </summary>
        public static string langSelectLanguage {
            get {
                return ResourceManager.GetString("langSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string langSpanish {
            get {
                return ResourceManager.GetString("langSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rules.
        /// </summary>
        public static string lobbyRules {
            get {
                return ResourceManager.GetString("lobbyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve sent a 6-digit code to:.
        /// </summary>
        public static string loginCode6DigitsSent {
            get {
                return ResourceManager.GetString("loginCode6DigitsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don&apos;t have an account?.
        /// </summary>
        public static string loginDontHaveAccount {
            get {
                return ResourceManager.GetString("loginDontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password.
        /// </summary>
        public static string loginForgotPassword {
            get {
                return ResourceManager.GetString("loginForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string loginGuest {
            get {
                return ResourceManager.GetString("loginGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log-In.
        /// </summary>
        public static string loginLogIn {
            get {
                return ResourceManager.GetString("loginLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string loginPassword {
            get {
                return ResourceManager.GetString("loginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *password required.
        /// </summary>
        public static string loginPasswordRequired {
            get {
                return ResourceManager.GetString("loginPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *password is too long.
        /// </summary>
        public static string loginPasswordTooLong {
            get {
                return ResourceManager.GetString("loginPasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as a guest.
        /// </summary>
        public static string loginPlayAsGuest {
            get {
                return ResourceManager.GetString("loginPlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign-In.
        /// </summary>
        public static string loginSignIn {
            get {
                return ResourceManager.GetString("loginSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *username required.
        /// </summary>
        public static string loginUsernameRequired {
            get {
                return ResourceManager.GetString("loginUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *username is too long.
        /// </summary>
        public static string loginUsernameTooLong {
            get {
                return ResourceManager.GetString("loginUsernameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code.
        /// </summary>
        public static string loginVerificationCode {
            get {
                return ResourceManager.GetString("loginVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check email.
        /// </summary>
        public static string loginVerifyEmail {
            get {
                return ResourceManager.GetString("loginVerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *wrong username or password, please try again.
        /// </summary>
        public static string loginWrongCredentials {
            get {
                return ResourceManager.GetString("loginWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, guest accounts cannot access this feature.
        /// </summary>
        public static string mainMenuGuestCannotAccess {
            get {
                return ResourceManager.GetString("mainMenuGuestCannotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logged-in as:.
        /// </summary>
        public static string mainMenuLoggedIn {
            get {
                return ResourceManager.GetString("mainMenuLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit.
        /// </summary>
        public static string mainMenuQuit {
            get {
                return ResourceManager.GetString("mainMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bystander tokens.
        /// </summary>
        public static string matchBystanderTokens {
            get {
                return ResourceManager.GetString("matchBystanderTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Party.
        /// </summary>
        public static string matchParty {
            get {
                return ResourceManager.GetString("matchParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timer tokens.
        /// </summary>
        public static string matchTimerTokens {
            get {
                return ResourceManager.GetString("matchTimerTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turn timer.
        /// </summary>
        public static string matchTurnTimer {
            get {
                return ResourceManager.GetString("matchTurnTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string profileEmail {
            get {
                return ResourceManager.GetString("profileEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        public static string profileLastName {
            get {
                return ResourceManager.GetString("profileLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string profileName {
            get {
                return ResourceManager.GetString("profileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name (optional).
        /// </summary>
        public static string profileOptionalLastName {
            get {
                return ResourceManager.GetString("profileOptionalLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name (Optional).
        /// </summary>
        public static string profileOptionalName {
            get {
                return ResourceManager.GetString("profileOptionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string profileProfile {
            get {
                return ResourceManager.GetString("profileProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social media links only support 30 characters.
        /// </summary>
        public static string profileSocialNetwork {
            get {
                return ResourceManager.GetString("profileSocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string resetChangePassword {
            get {
                return ResourceManager.GetString("resetChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ve sent a code to your email. Please check your inbox and enter it where requested..
        /// </summary>
        public static string resetCodeSend {
            get {
                return ResourceManager.GetString("resetCodeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not send code.
        /// </summary>
        public static string resetCodeSendFailed {
            get {
                return ResourceManager.GetString("resetCodeSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Associated email.
        /// </summary>
        public static string resetEmail {
            get {
                return ResourceManager.GetString("resetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter username and email.
        /// </summary>
        public static string resetMissingUserOrEmail {
            get {
                return ResourceManager.GetString("resetMissingUserOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string resetNewPassword {
            get {
                return ResourceManager.GetString("resetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not change password.
        /// </summary>
        public static string resetPasswordChangeFailed {
            get {
                return ResourceManager.GetString("resetPasswordChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be between 10 and 16 characters.
        /// </summary>
        public static string resetPasswordLengthInvalid {
            get {
                return ResourceManager.GetString("resetPasswordLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        public static string resetPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("resetPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Received code.
        /// </summary>
        public static string resetReceivedCode {
            get {
                return ResourceManager.GetString("resetReceivedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send code.
        /// </summary>
        public static string resetSendCode {
            get {
                return ResourceManager.GetString("resetSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset password.
        /// </summary>
        public static string resetTitle {
            get {
                return ResourceManager.GetString("resetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My score.
        /// </summary>
        public static string scoresMyScore {
            get {
                return ResourceManager.GetString("scoresMyScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh.
        /// </summary>
        public static string scoresRefresh {
            get {
                return ResourceManager.GetString("scoresRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code must have 6 digits..
        /// </summary>
        public static string signInCodeMustHave6Digits {
            get {
                return ResourceManager.GetString("signInCodeMustHave6Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string signInConfirmPassword {
            get {
                return ResourceManager.GetString("signInConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email format is invalid.
        /// </summary>
        public static string signInEmailInvalidFormat {
            get {
                return ResourceManager.GetString("signInEmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is required.
        /// </summary>
        public static string signInEmailRequired {
            get {
                return ResourceManager.GetString("signInEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error confirming registration: .
        /// </summary>
        public static string signInErrorConfirmingRegistration {
            get {
                return ResourceManager.GetString("signInErrorConfirmingRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error starting registration: .
        /// </summary>
        public static string signInErrorStartingRegistration {
            get {
                return ResourceManager.GetString("signInErrorStartingRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The maximum length of the first name is 20 characters.
        /// </summary>
        public static string signInFirstNameMaxLength {
            get {
                return ResourceManager.GetString("signInFirstNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name may contain letters (with accents) and spaces only.
        /// </summary>
        public static string signInFirstNameOnlyLettersSpacesAccents {
            get {
                return ResourceManager.GetString("signInFirstNameOnlyLettersSpacesAccents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name is required.
        /// </summary>
        public static string signInFirstNameRequired {
            get {
                return ResourceManager.GetString("signInFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The maximum length of the last name is 30 characters.
        /// </summary>
        public static string signInLastNameMaxLength {
            get {
                return ResourceManager.GetString("signInLastNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name may contain letters (with accents) and spaces only.
        /// </summary>
        public static string signInLastNameOnlyLettersSpacesAccents {
            get {
                return ResourceManager.GetString("signInLastNameOnlyLettersSpacesAccents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los apellidos son obligatorios.
        /// </summary>
        public static string signInLastNameRequired {
            get {
                return ResourceManager.GetString("signInLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are not pending requests..
        /// </summary>
        public static string signInNoPendingRequests {
            get {
                return ResourceManager.GetString("signInNoPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one digit.
        /// </summary>
        public static string signInPasswordAtLeastOneDigit {
            get {
                return ResourceManager.GetString("signInPasswordAtLeastOneDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one lowercase letter.
        /// </summary>
        public static string signInPasswordAtLeastOneLowercaseLetter {
            get {
                return ResourceManager.GetString("signInPasswordAtLeastOneLowercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one special character.
        /// </summary>
        public static string signInPasswordAtLeastOneSpecialCharacter {
            get {
                return ResourceManager.GetString("signInPasswordAtLeastOneSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one uppercase letter.
        /// </summary>
        public static string signInPasswordAtLeastOneUppercaseLetter {
            get {
                return ResourceManager.GetString("signInPasswordAtLeastOneUppercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be at most {0} characters.
        /// </summary>
        public static string signInPasswordMaxLength {
            get {
                return ResourceManager.GetString("signInPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be at least {0} characters.
        /// </summary>
        public static string signInPasswordMinLength {
            get {
                return ResourceManager.GetString("signInPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must not contain more than 3 consecutive digits.
        /// </summary>
        public static string signInPasswordNotContainMoreThan3ConsecutiveDigits {
            get {
                return ResourceManager.GetString("signInPasswordNotContainMoreThan3ConsecutiveDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is required.
        /// </summary>
        public static string signInPasswordRequired {
            get {
                return ResourceManager.GetString("signInPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        public static string signInPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("signInPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string signInRegister {
            get {
                return ResourceManager.GetString("signInRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration could not be started..
        /// </summary>
        public static string signInRegistrationCouldNotBeStarted {
            get {
                return ResourceManager.GetString("signInRegistrationCouldNotBeStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username is required.
        /// </summary>
        public static string signInUsernameRequired {
            get {
                return ResourceManager.GetString("signInUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string socialAccept {
            get {
                return ResourceManager.GetString("socialAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string socialAddFriend {
            get {
                return ResourceManager.GetString("socialAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete friend.
        /// </summary>
        public static string socialDeleteFriend {
            get {
                return ResourceManager.GetString("socialDeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject.
        /// </summary>
        public static string socialReject {
            get {
                return ResourceManager.GetString("socialReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requests.
        /// </summary>
        public static string socialRequests {
            get {
                return ResourceManager.GetString("socialRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search for a friend.
        /// </summary>
        public static string socialSearchForAFriend {
            get {
                return ResourceManager.GetString("socialSearchForAFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search results.
        /// </summary>
        public static string socialSearchResults {
            get {
                return ResourceManager.GetString("socialSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Effects.
        /// </summary>
        public static string soundGameEffects {
            get {
                return ResourceManager.GetString("soundGameEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master Volume.
        /// </summary>
        public static string soundMasterVolume {
            get {
                return ResourceManager.GetString("soundMasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music Volume.
        /// </summary>
        public static string soundMusicVolume {
            get {
                return ResourceManager.GetString("soundMusicVolume", resourceCulture);
            }
        }
    }
}
