//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenamesGame.MatchmakingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchmakingService.AuthenticationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchmakingService.SignInRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchmakingService.ConfirmEmailRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchmakingService.CreateLobbyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchmakingService.JoinPartyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchmakingService.FriendshipRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchmakingService.CommunicationRequest))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.StatusCode StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.StatusCode StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class AuthenticationRequest : CodenamesGame.MatchmakingService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignInRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class SignInRequest : CodenamesGame.MatchmakingService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEmailDuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEmailValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPasswordValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUsernameDuplicateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEmailDuplicate {
            get {
                return this.IsEmailDuplicateField;
            }
            set {
                if ((this.IsEmailDuplicateField.Equals(value) != true)) {
                    this.IsEmailDuplicateField = value;
                    this.RaisePropertyChanged("IsEmailDuplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEmailValid {
            get {
                return this.IsEmailValidField;
            }
            set {
                if ((this.IsEmailValidField.Equals(value) != true)) {
                    this.IsEmailValidField = value;
                    this.RaisePropertyChanged("IsEmailValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPasswordValid {
            get {
                return this.IsPasswordValidField;
            }
            set {
                if ((this.IsPasswordValidField.Equals(value) != true)) {
                    this.IsPasswordValidField = value;
                    this.RaisePropertyChanged("IsPasswordValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUsernameDuplicate {
            get {
                return this.IsUsernameDuplicateField;
            }
            set {
                if ((this.IsUsernameDuplicateField.Equals(value) != true)) {
                    this.IsUsernameDuplicateField = value;
                    this.RaisePropertyChanged("IsUsernameDuplicate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmEmailRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class ConfirmEmailRequest : CodenamesGame.MatchmakingService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemainingAttemptsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemainingAttempts {
            get {
                return this.RemainingAttemptsField;
            }
            set {
                if ((this.RemainingAttemptsField.Equals(value) != true)) {
                    this.RemainingAttemptsField = value;
                    this.RaisePropertyChanged("RemainingAttempts");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateLobbyRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class CreateLobbyRequest : CodenamesGame.MatchmakingService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JoinPartyRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class JoinPartyRequest : CodenamesGame.MatchmakingService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Party PartyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Party Party {
            get {
                return this.PartyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyField, value) != true)) {
                    this.PartyField = value;
                    this.RaisePropertyChanged("Party");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendshipRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class FriendshipRequest : CodenamesGame.MatchmakingService.Request {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommunicationRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class CommunicationRequest : CodenamesGame.MatchmakingService.Request {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    public enum StatusCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPDATED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONFLICT = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_CANCEL = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_DISCONNECT = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_UNREACHABLE = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_TIMEOUT = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MISSING_DATA = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WRONG_DATA = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_FOUND = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNAUTHORIZED = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNALLOWED = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_ERROR = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_UNAVAIBLE = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_TIMEOUT = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_UNREACHABLE = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLIENT_ERROR = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACCOUNT_BANNED = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORT_CREATED = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORT_DUPLICATED = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USER_KICKED_AND_BANNED = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRIEND_REQUEST_SENT = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRIEND_ADDED = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRIEND_REMOVED = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRIEND_REQUEST_REJECTED = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALREADY_FRIENDS = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRIEND_REQUEST_ALREADY_SENT = 27,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Party", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class Party : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Player PartyGuestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Player PartyHostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Player PartyGuest {
            get {
                return this.PartyGuestField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyGuestField, value) != true)) {
                    this.PartyGuestField = value;
                    this.RaisePropertyChanged("PartyGuest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Player PartyHost {
            get {
                return this.PartyHostField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyHostField, value) != true)) {
                    this.PartyHostField = value;
                    this.RaisePropertyChanged("PartyHost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvatarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscordUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstagramUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> PlayerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvatarID {
            get {
                return this.AvatarIDField;
            }
            set {
                if ((this.AvatarIDField.Equals(value) != true)) {
                    this.AvatarIDField = value;
                    this.RaisePropertyChanged("AvatarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscordUsername {
            get {
                return this.DiscordUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscordUsernameField, value) != true)) {
                    this.DiscordUsernameField = value;
                    this.RaisePropertyChanged("DiscordUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookUsername {
            get {
                return this.FacebookUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookUsernameField, value) != true)) {
                    this.FacebookUsernameField = value;
                    this.RaisePropertyChanged("FacebookUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstagramUsername {
            get {
                return this.InstagramUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.InstagramUsernameField, value) != true)) {
                    this.InstagramUsernameField = value;
                    this.RaisePropertyChanged("InstagramUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PlayerID {
            get {
                return this.PlayerIDField;
            }
            set {
                if ((this.PlayerIDField.Equals(value) != true)) {
                    this.PlayerIDField = value;
                    this.RaisePropertyChanged("PlayerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchConfiguration", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class MatchConfiguration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Player CompanionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.MatchRules MatchRulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Player RequesterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Player Companion {
            get {
                return this.CompanionField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanionField, value) != true)) {
                    this.CompanionField = value;
                    this.RaisePropertyChanged("Companion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.MatchRules MatchRules {
            get {
                return this.MatchRulesField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchRulesField, value) != true)) {
                    this.MatchRulesField = value;
                    this.RaisePropertyChanged("MatchRules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Player Requester {
            get {
                return this.RequesterField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterField, value) != true)) {
                    this.RequesterField = value;
                    this.RaisePropertyChanged("Requester");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchRules", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class MatchRules : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BystanderTokensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Gamemode GamemodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimerTokensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnTimerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BystanderTokens {
            get {
                return this.BystanderTokensField;
            }
            set {
                if ((this.BystanderTokensField.Equals(value) != true)) {
                    this.BystanderTokensField = value;
                    this.RaisePropertyChanged("BystanderTokens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Gamemode Gamemode {
            get {
                return this.GamemodeField;
            }
            set {
                if ((this.GamemodeField.Equals(value) != true)) {
                    this.GamemodeField = value;
                    this.RaisePropertyChanged("Gamemode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimerTokens {
            get {
                return this.TimerTokensField;
            }
            set {
                if ((this.TimerTokensField.Equals(value) != true)) {
                    this.TimerTokensField = value;
                    this.RaisePropertyChanged("TimerTokens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnTimer {
            get {
                return this.TurnTimerField;
            }
            set {
                if ((this.TurnTimerField.Equals(value) != true)) {
                    this.TurnTimerField = value;
                    this.RaisePropertyChanged("TurnTimer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gamemode", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    public enum Gamemode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NORMAL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUSTOM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COUNTERINTELLIGENCE = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] BoardPlayerOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] BoardPlayerTwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Player CompanionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MatchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Player RequesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.MatchRules RulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] SelectedWordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] BoardPlayerOne {
            get {
                return this.BoardPlayerOneField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardPlayerOneField, value) != true)) {
                    this.BoardPlayerOneField = value;
                    this.RaisePropertyChanged("BoardPlayerOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] BoardPlayerTwo {
            get {
                return this.BoardPlayerTwoField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardPlayerTwoField, value) != true)) {
                    this.BoardPlayerTwoField = value;
                    this.RaisePropertyChanged("BoardPlayerTwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Player Companion {
            get {
                return this.CompanionField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanionField, value) != true)) {
                    this.CompanionField = value;
                    this.RaisePropertyChanged("Companion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MatchID {
            get {
                return this.MatchIDField;
            }
            set {
                if ((this.MatchIDField.Equals(value) != true)) {
                    this.MatchIDField = value;
                    this.RaisePropertyChanged("MatchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Player Requester {
            get {
                return this.RequesterField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterField, value) != true)) {
                    this.RequesterField = value;
                    this.RaisePropertyChanged("Requester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.MatchRules Rules {
            get {
                return this.RulesField;
            }
            set {
                if ((object.ReferenceEquals(this.RulesField, value) != true)) {
                    this.RulesField = value;
                    this.RaisePropertyChanged("Rules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SelectedWords {
            get {
                return this.SelectedWordsField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedWordsField, value) != true)) {
                    this.SelectedWordsField = value;
                    this.RaisePropertyChanged("SelectedWords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchmakingService.IMatchmakingManager", CallbackContract=typeof(CodenamesGame.MatchmakingService.IMatchmakingManagerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMatchmakingManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/Connect", ReplyAction="http://tempuri.org/IMatchmakingManager/ConnectResponse")]
        CodenamesGame.MatchmakingService.CommunicationRequest Connect(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/Connect", ReplyAction="http://tempuri.org/IMatchmakingManager/ConnectResponse")]
        System.Threading.Tasks.Task<CodenamesGame.MatchmakingService.CommunicationRequest> ConnectAsync(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/Disconnect")]
        void Disconnect(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/Disconnect")]
        System.Threading.Tasks.Task DisconnectAsync(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/RequestArrangedMatch", ReplyAction="http://tempuri.org/IMatchmakingManager/RequestArrangedMatchResponse")]
        CodenamesGame.MatchmakingService.CommunicationRequest RequestArrangedMatch(CodenamesGame.MatchmakingService.MatchConfiguration configuration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/RequestArrangedMatch", ReplyAction="http://tempuri.org/IMatchmakingManager/RequestArrangedMatchResponse")]
        System.Threading.Tasks.Task<CodenamesGame.MatchmakingService.CommunicationRequest> RequestArrangedMatchAsync(CodenamesGame.MatchmakingService.MatchConfiguration configuration);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/ConfirmMatchReceived")]
        void ConfirmMatchReceived(System.Guid playerID, System.Guid matchID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/ConfirmMatchReceived")]
        System.Threading.Tasks.Task ConfirmMatchReceivedAsync(System.Guid playerID, System.Guid matchID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/RequestMatchCancel")]
        void RequestMatchCancel(System.Guid playerID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/RequestMatchCancel")]
        System.Threading.Tasks.Task RequestMatchCancelAsync(System.Guid playerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchmakingManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/NotifyRequestPending")]
        void NotifyRequestPending(System.Guid requesterID, System.Guid companionID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/NotifyMatchReady")]
        void NotifyMatchReady(CodenamesGame.MatchmakingService.Match match);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/NotifyPlayersReady")]
        void NotifyPlayersReady(System.Guid matchID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/NotifyMatchCanceled")]
        void NotifyMatchCanceled(System.Guid matchID, CodenamesGame.MatchmakingService.StatusCode reason);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchmakingManagerChannel : CodenamesGame.MatchmakingService.IMatchmakingManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchmakingManagerClient : System.ServiceModel.DuplexClientBase<CodenamesGame.MatchmakingService.IMatchmakingManager>, CodenamesGame.MatchmakingService.IMatchmakingManager {
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public CodenamesGame.MatchmakingService.CommunicationRequest Connect(System.Guid playerID) {
            return base.Channel.Connect(playerID);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.MatchmakingService.CommunicationRequest> ConnectAsync(System.Guid playerID) {
            return base.Channel.ConnectAsync(playerID);
        }
        
        public void Disconnect(System.Guid playerID) {
            base.Channel.Disconnect(playerID);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(System.Guid playerID) {
            return base.Channel.DisconnectAsync(playerID);
        }
        
        public CodenamesGame.MatchmakingService.CommunicationRequest RequestArrangedMatch(CodenamesGame.MatchmakingService.MatchConfiguration configuration) {
            return base.Channel.RequestArrangedMatch(configuration);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.MatchmakingService.CommunicationRequest> RequestArrangedMatchAsync(CodenamesGame.MatchmakingService.MatchConfiguration configuration) {
            return base.Channel.RequestArrangedMatchAsync(configuration);
        }
        
        public void ConfirmMatchReceived(System.Guid playerID, System.Guid matchID) {
            base.Channel.ConfirmMatchReceived(playerID, matchID);
        }
        
        public System.Threading.Tasks.Task ConfirmMatchReceivedAsync(System.Guid playerID, System.Guid matchID) {
            return base.Channel.ConfirmMatchReceivedAsync(playerID, matchID);
        }
        
        public void RequestMatchCancel(System.Guid playerID) {
            base.Channel.RequestMatchCancel(playerID);
        }
        
        public System.Threading.Tasks.Task RequestMatchCancelAsync(System.Guid playerID) {
            return base.Channel.RequestMatchCancelAsync(playerID);
        }
    }
}
