//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodenamesGame.MatchmakingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchConfiguration", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class MatchConfiguration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Player CompanionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.MatchRules MatchRulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Player RequesterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Player Companion {
            get {
                return this.CompanionField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanionField, value) != true)) {
                    this.CompanionField = value;
                    this.RaisePropertyChanged("Companion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.MatchRules MatchRules {
            get {
                return this.MatchRulesField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchRulesField, value) != true)) {
                    this.MatchRulesField = value;
                    this.RaisePropertyChanged("MatchRules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Player Requester {
            get {
                return this.RequesterField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterField, value) != true)) {
                    this.RequesterField = value;
                    this.RaisePropertyChanged("Requester");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvatarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscordUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstagramUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> PlayerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvatarID {
            get {
                return this.AvatarIDField;
            }
            set {
                if ((this.AvatarIDField.Equals(value) != true)) {
                    this.AvatarIDField = value;
                    this.RaisePropertyChanged("AvatarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscordUsername {
            get {
                return this.DiscordUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscordUsernameField, value) != true)) {
                    this.DiscordUsernameField = value;
                    this.RaisePropertyChanged("DiscordUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookUsername {
            get {
                return this.FacebookUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookUsernameField, value) != true)) {
                    this.FacebookUsernameField = value;
                    this.RaisePropertyChanged("FacebookUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstagramUsername {
            get {
                return this.InstagramUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.InstagramUsernameField, value) != true)) {
                    this.InstagramUsernameField = value;
                    this.RaisePropertyChanged("InstagramUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PlayerID {
            get {
                return this.PlayerIDField;
            }
            set {
                if ((this.PlayerIDField.Equals(value) != true)) {
                    this.PlayerIDField = value;
                    this.RaisePropertyChanged("PlayerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchRules", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class MatchRules : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BystanderTokensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Gamemode GamemodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimerTokensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnTimerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BystanderTokens {
            get {
                return this.BystanderTokensField;
            }
            set {
                if ((this.BystanderTokensField.Equals(value) != true)) {
                    this.BystanderTokensField = value;
                    this.RaisePropertyChanged("BystanderTokens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Gamemode Gamemode {
            get {
                return this.GamemodeField;
            }
            set {
                if ((this.GamemodeField.Equals(value) != true)) {
                    this.GamemodeField = value;
                    this.RaisePropertyChanged("Gamemode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimerTokens {
            get {
                return this.TimerTokensField;
            }
            set {
                if ((this.TimerTokensField.Equals(value) != true)) {
                    this.TimerTokensField = value;
                    this.RaisePropertyChanged("TimerTokens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnTimer {
            get {
                return this.TurnTimerField;
            }
            set {
                if ((this.TurnTimerField.Equals(value) != true)) {
                    this.TurnTimerField = value;
                    this.RaisePropertyChanged("TurnTimer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gamemode", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    public enum Gamemode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NORMAL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUSTOM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COUNTERINTELLIGENCE = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchmakingService.CommunicationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchmakingService.LoginRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodenamesGame.MatchmakingService.MatchRequest))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.StatusCode StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.StatusCode StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommunicationRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class CommunicationRequest : CodenamesGame.MatchmakingService.Request {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class LoginRequest : CodenamesGame.MatchmakingService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchRequest", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class MatchRequest : CodenamesGame.MatchmakingService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Match MatchField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Match Match {
            get {
                return this.MatchField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchField, value) != true)) {
                    this.MatchField = value;
                    this.RaisePropertyChanged("Match");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    public enum StatusCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CREATED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPDATED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MISSING_DATA = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WRONG_DATA = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNAUTHORIZED = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_ERROR = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_UNAVAIBLE = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_TIMEOUT = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO.DataContract")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] BoardPlayerOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] BoardPlayerTwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Player CompanionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MatchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.Player RequesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CodenamesGame.MatchmakingService.MatchRules RulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] SelectedWordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] BoardPlayerOne {
            get {
                return this.BoardPlayerOneField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardPlayerOneField, value) != true)) {
                    this.BoardPlayerOneField = value;
                    this.RaisePropertyChanged("BoardPlayerOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] BoardPlayerTwo {
            get {
                return this.BoardPlayerTwoField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardPlayerTwoField, value) != true)) {
                    this.BoardPlayerTwoField = value;
                    this.RaisePropertyChanged("BoardPlayerTwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Player Companion {
            get {
                return this.CompanionField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanionField, value) != true)) {
                    this.CompanionField = value;
                    this.RaisePropertyChanged("Companion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MatchID {
            get {
                return this.MatchIDField;
            }
            set {
                if ((this.MatchIDField.Equals(value) != true)) {
                    this.MatchIDField = value;
                    this.RaisePropertyChanged("MatchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.Player Requester {
            get {
                return this.RequesterField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterField, value) != true)) {
                    this.RequesterField = value;
                    this.RaisePropertyChanged("Requester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CodenamesGame.MatchmakingService.MatchRules Rules {
            get {
                return this.RulesField;
            }
            set {
                if ((object.ReferenceEquals(this.RulesField, value) != true)) {
                    this.RulesField = value;
                    this.RaisePropertyChanged("Rules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SelectedWords {
            get {
                return this.SelectedWordsField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedWordsField, value) != true)) {
                    this.SelectedWordsField = value;
                    this.RaisePropertyChanged("SelectedWords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchmakingService.IMatchmakingManager", CallbackContract=typeof(CodenamesGame.MatchmakingService.IMatchmakingManagerCallback))]
    public interface IMatchmakingManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/GetMatchWithAFriend", ReplyAction="http://tempuri.org/IMatchmakingManager/GetMatchWithAFriendResponse")]
        CodenamesGame.MatchmakingService.MatchRequest GetMatchWithAFriend(CodenamesGame.MatchmakingService.MatchConfiguration configuration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/GetMatchWithAFriend", ReplyAction="http://tempuri.org/IMatchmakingManager/GetMatchWithAFriendResponse")]
        System.Threading.Tasks.Task<CodenamesGame.MatchmakingService.MatchRequest> GetMatchWithAFriendAsync(CodenamesGame.MatchmakingService.MatchConfiguration configuration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/CancelMatch", ReplyAction="http://tempuri.org/IMatchmakingManager/CancelMatchResponse")]
        CodenamesGame.MatchmakingService.CommunicationRequest CancelMatch();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingManager/CancelMatch", ReplyAction="http://tempuri.org/IMatchmakingManager/CancelMatchResponse")]
        System.Threading.Tasks.Task<CodenamesGame.MatchmakingService.CommunicationRequest> CancelMatchAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchmakingManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/ReceiveMatch")]
        void ReceiveMatch(CodenamesGame.MatchmakingService.Match match);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchmakingManager/NotifyMatchCanceled")]
        void NotifyMatchCanceled();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchmakingManagerChannel : CodenamesGame.MatchmakingService.IMatchmakingManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchmakingManagerClient : System.ServiceModel.DuplexClientBase<CodenamesGame.MatchmakingService.IMatchmakingManager>, CodenamesGame.MatchmakingService.IMatchmakingManager {
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public CodenamesGame.MatchmakingService.MatchRequest GetMatchWithAFriend(CodenamesGame.MatchmakingService.MatchConfiguration configuration) {
            return base.Channel.GetMatchWithAFriend(configuration);
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.MatchmakingService.MatchRequest> GetMatchWithAFriendAsync(CodenamesGame.MatchmakingService.MatchConfiguration configuration) {
            return base.Channel.GetMatchWithAFriendAsync(configuration);
        }
        
        public CodenamesGame.MatchmakingService.CommunicationRequest CancelMatch() {
            return base.Channel.CancelMatch();
        }
        
        public System.Threading.Tasks.Task<CodenamesGame.MatchmakingService.CommunicationRequest> CancelMatchAsync() {
            return base.Channel.CancelMatchAsync();
        }
    }
}
